openapi: 3.0.0

components:
  parameters:
    id:
      name: exampleId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: uuid
