openapi: 3.0.0

components:
  responses:
    success:
      description: "get some examples"
      headers: 
        API-Version:
          description: indicates the version
          schema:
            description: versioning
            type: string
            pattern: "^apiversion"
      content:
        application/vnd.api+json:
          schema:
            type: boolean
