openapi: 3.0.0

components:
  parameters:
    id:
      name: exampleId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: uuid

  schemas:
    links:
      type: object
      properties:
        first:
          type: string
          format: uri
          maxLength: 256
        last:
          type: string
          format: uri
          maxLength: 256
    
    version:
      description: Semantic Version
      type: string
      pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
