openapi: 3.0.0

components:
  responses:
    success:
      description: "get some examples"
      headers: 
        API-Version:
          description: indicates the version
          schema:
            description: versioning
            type: string
            pattern: "^apiversion"
      content:
        application/vnd.api+json:
          schema:
            type: boolean
    success-collection:
      description: collection response
      headers:
        API-Version:
          description: indicates the Semantic Version that responds to the request
          schema:
            $ref: 'shared-domain.yml#/components/schemas/version'
      content:
        application/vnd.api+json:
          schema:
            allOf:
              - $ref: 'shared-domain.yml#/components/schemas/links'
              - $ref: '#/components/schemas/collection'

  schemas:
    collection:
      type: object
      properties:
        data:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/identifier"

    identifier:
      properties:
        id:
          type: string
          minLength: 36
          maxLength: 36
          format: uuid
        type:
          type: string
          maxLength: 64
          example: "examples"
          pattern: "^examples"
