openapi: 3.0.0
info:
  version: 1.0.0

paths:
  "/example":
      get:
        summary: Retrieves examples
        responses:
          200: 
            $ref: "#/components/responses/success"

components:
  responses:
    success:
      description: "get examples"
      schema:
        type: boolean
