openapi: 3.0.0
info:
  version: 1.0.0

paths:
  "/example":
      get:
        summary: Retrieves examples
        responses:
          200: 
            $ref: "./domainspec.yml#/components/responses/success"
