openapi: 3.0.0
info:
  version: 1.0.0

paths:
  "/example":
      get:
        summary: Retrieves examples
        responses:
          200: 
            $ref: "#/components/responses/success"

components:
  responses:
    success:
      description: "get some examples"
      headers: 
        API-Version:
          description: indicates the version
          schema:
            description: versioning
            type: string
            pattern: "^apiversion"
      content:
        application/vnd.api+json:
          schema:
            type: boolean
