openapi: 3.0.0
info:
  version: 1.0.0

paths:
  "/example":
      get:
        summary: Retrieves examples
        responses:
          200: 
            description: "get examples"
            schema:
              type: boolean
